import { Metadata } from 'next';
import { SignInContainer } from '@modules/auth/pages';

export const metadata: Metadata = {
    title: 'Sign In',
    description: 'Generated by create next app',
};

export default function Page() {
    return <SignInContainer />;
}
